---
# remiのリポジトリをインストール
- name: install remi repository
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
# php70のインストール
- name: install php70
  yum:
    name: "{{ item }}"
    enablerepo: remi,remi-php70
    state: present
  with_items:
    - php70
    - php70-php
    - php70-php-devel
    - php70-php-xml
    - php70-php-mbstring
    - php70-php-gd
    - php70-php-pgsql
    - php70-php-mysqlnd
    - php70-php-mcrypt
    - php70-php-intl
    - php70-php-opcache
    - php70-php-pdo
    - php70-php-json
    - php70-php-pecl-zip
  notify:
    - restart httpd
- name: install apcu
  yum:
    name: php70-php-pecl-apcu
    enablerepo: remi,remi-php70
    state: present
  when: centos7_remi_php70_enable_apcu
  notify:
    - restart httpd
- name: install litespeed
  yum:
    name: php70-php-litespeed
    enablerepo: remi,remi-php70
    state: present
  when: centos7_remi_php70_enable_litespeed
- name: setup /usr/local/lsws/fcgi-bin/lsphp5
  file:
    src: /opt/remi/php70/root/bin/lsphp
    dest: /usr/local/lsws/fcgi-bin/lsphp5
    state: link
    force: yes
  when: centos7_remi_php70_enable_litespeed
- name: install fpm
  yum:
    name: php70-php-fpm
    enablerepo: remi,remi-php70
    state: present
  when: centos7_remi_php70_enable_fpm
# ここから https://gist.github.com/debility/8838906 を反映
- name: config PHP
  copy:
    src: 99-my.ini
    dest: /etc/opt/remi/php70/php.d/99-my.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
# ここまで https://gist.github.com/debility/8838906 を反映
- name: config OPCache
  lineinfile:
    dest: /etc/opt/remi/php70/php.d/10-opcache.ini
    regexp: "opcache\\.enable_cli="
    line: "opcache.enable_cli=1"
  notify:
    - restart httpd
# ログイン時に有効化する
- name: config for login
  copy:
    src: enablephp70.sh
    dest: /etc/profile.d/enablephp70.sh
    owner: root
    group: root
    mode: 0644
