---
# 不要なサービスの停止と自動起動をオフに
- name: stop services
  service: name={{ item }} state=stopped
  with_items:
    - iptables
    - ip6tables
    - postfix
  ignore_errors: true
- name: disable services
  service: name={{ item }} enabled=no
  with_items:
    - iptables
    - ip6tables
    - postfix
    - iscsi
    - iscsid
    - auditd
    - mdmonitor
    - netfs
  ignore_errors: true
